//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub twitch_uuid: Uuid,
    pub name: String,
    pub action_points: Option<i32>,
    pub refresh_hand_date: Option<DateTime>,
    pub last_log_in: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tamago::Entity")]
    Tamago,
}

impl Related<super::tamago::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tamago.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
