ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY . .

RUN npm ci --audit false --fund false

ENTRYPOINT ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "3001"]

EXPOSE 3001