ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY package*.json .

RUN npm ci --audit false --fund false

COPY . .

ENTRYPOINT ["npm", "run", "dev", "--", "--host"]

EXPOSE 5173